---
- hosts: all
  become: yes

 # import as tarefas/handlers do outro arquivo.
  handlers:
  - import_tasks: handlers/apache.yml
  
  pre_tasks:
    - name : Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
  - import_tasks: tasks/tasks.yml

- import_playbook: app.yml