---
  - name: Ensure Apache  is installed.
    yum:
      name: "{{ apache_package }}"
      state: present     

  - name: Copy test config files.
    copy:
      src: files/test.conf
      dest: "{{ apache_config_dir }}/test.conf"
    notify: restart apache

  - name: Ensure Apache is running.
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes




 

